### ISSUE TITLE
Cannot open Simulink model with MATLAB 2020a

### ISSUE THREAD

**Issue by s18el05** [MustafaSaraoglu/AutonomousVehicleModeling#19]
Hello,
I can't open the simulink model ManeuvrePlanning.slx using MATLAB 2020a, can you please modify it to be able to open?
![image](https://user-images.githubusercontent.com/97359621/200286499-52876df8-d0dc-4359-a956-36d157e492e1.png)

**Comment by MustafaSaraoglu** [comment]
Thank you for your interest! I have added the R2020a version of the Simulink model. To make sure that the scripts work as intended, rename the original "ManeuverPlanning.slx" to some other name and double click on the new file "ManeuverPlanning.slx.r2020a" to save it as the new "ManeuverPlanning.slx", which should work in the R2020a version. Let me know if there are any other issues!

**Comment by s18el05** [comment]
Thank you a lot for the quick reponse!
